config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create] do
    resources :items, only: :show
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :items do
    get :download, on: :collection
    get :download_my
  end
  resources :folders
  resources :profiles
  resources :addresses
  root to: 'items#index'
end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :country, length: { maximum: 25 }
  validates :city, length: { maximum: 25 }
  validates :street, length: { maximum: 30 }
  validates :house_number, length: { maximum: 10 }
  belongs_to :profile
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  validates :name, presence: true
  has_many :children, class_name: "Folder", foreign_key: "parent_id", dependent: :destroy
  has_many :items, dependent: :destroy
  belongs_to :parent, class_name: "Folder"
  belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
  mount_uploader :file, FileUploader
  belongs_to :user
  belongs_to :folder

  before_create :generate_token, :set_name

  private

  def generate_token
    self.token = SecureRandom.urlsafe_base64(64, true)
  end

  def set_name
    self.name = File.basename self.file.path
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  mount_uploader :photo, FileUploader
  validates :name, length: { maximum: 60 }
  validates :birthday, presence: :true
  belongs_to :user
  has_many :addresses, dependent: :destroy
  accepts_nested_attributes_for :addresses, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_secure_password

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }
  has_many :folders, dependent: :destroy
  has_many :items, dependent: :destroy
  has_one :profile, dependent: :destroy

  after_create :build_profile

  def build_profile
    Profile.create(user: self, birthday: Time.now)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :init_item
  before_filter :authenticate


  def init_item
    @item = Item.new
  end

  def check_user
    redirect_to root_path if logged_in?
  end

  def authenticate
    redirect_to new_session_path unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def content_verification(file)
    image_types = ["image/jpeg", "image/jpg", "image/png", "image/bmb"]
    audio_types = ["audio/mp3", "audio/mid", "audio/wav", "audio/x-flac", "audio/aac", "audio/mpeg"]
    video_types = ["application/mp4", "application/mkv", "application/3gp", "application/avi", "video/x-matroska", "video/x-msvideo", "video/quicktime", "video/mp4"]
    return 1 if image_types.include? file.content_type
    return 2 if audio_types.include? file.content_type
    return 3 if video_types.include? file.content_type
    return 0
  end
  helper_method [:current_user, :content_verification]
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  respond_to :html, :json

  def create
    current_user.folders.create(name: "Нова тека", parent_id: params[:parent_id])
    redirect_to :back
  end

  def show
    @folder = current_user.folders.find_by(id: params[:id])
  end

  def edit
    respond_with @folder
  end

  def update
    folder = current_user.folders.find_by(id: params[:id])
    if folder.update(folder_params)
      redirect_to :back, notice: 'Тека успішно перейменована'
    else
      redirect_to :back
      flash[:error] = 'Теку не вдалося перейменувати'
    end
  end

  def destroy
    folder = current_user.folders.find_by(id: params[:id])
    if folder.destroy
      respond_to do |format|
        format.js { flash[:notice] = 'Тека успішно видалена' }
      end
    end
  end

  private

  def folder_params
    params.permit(:name)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_filter :authenticate, only: [:show, :download]
  before_filter :get_item, only: [:show, :download]

  def index
    @folders = current_user.folders.where('parent_id IS NULL')
    @items = Item.where('folder_id IS NULL').page(1).per(20)
  end

  def create
    folder = Folder.find_by(id: params[:item][:folder_id])
    if folder
      @item = folder.items.new(params_item)
      @item.user_id = folder.user_id
    else
      @item = current_user.items.new(params_item)
    end
    if @item.save
      flash[:notice] = "Файл(и) успішно завантажені"
      render nothing: true
    else
      render 'new'
    end
  end

  def edit
    @item = current_user.items.find_by(id: params[:id])
  end

  def update
    @item = current_user.items.find_by(id: params[:id])
    if @item.update(params_item)
      flash[:success] = "File updated"
    else
      render 'edit'
    end
  end

  def destroy
    item = current_user.items.find_by(id: params[:id])
    item.destroy! if item
    flash[:notice] = 'Файл успішно видалений'
    redirect_to root_path
  end

  def download
    send_file(@item.file.path)
  end

  def download_my
    item = current_user.items.find_by(id: params[:item_id])
    send_file(item.file.path)
  end

  private

  def params_item
    params.permit(:file, :name)
  end

  def get_item
    user = User.find_by(id: params[:user_id])
    @item = user.items.find_by(token: params[:id])
    redirect_to root_path unless user && @item
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def edit
    @profile = Profile.find_by(id: params[:id])
  end

  def update
    if current_user.profile.update(profile_params)
      redirect_to :back, notice: 'Профіль успішно оновлений'
    else
      redirect_to :back
      flash[:error] = 'Профіль не вдалося оновити'
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:name, :photo, :birthday, addresses_attributes: [:id, :country, :city, :street, :house_number, :_destroy])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate, only: [:new, :create]
  before_filter :check_user, except: :destroy

  def create
    user = User.find_by(email: params[:sessions][:email].downcase)
    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
      flash[:notice] = "Ви увійшли як #{current_user.email}"
      redirect_to root_path
    else
      flash.now[:danger] = 'Неправильно введено електронну пошту або пароль'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authenticate, only: [:new, :create]
  before_filter :check_user

  def new
    @user = User.new
  end

  def create
    user = User.new(params_user)
    if user.save
      flash[:notice] = "Користувач успішно створений"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def params_user
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def check_render_file(i)
    if i.image?
      link_to i.file.url, id: "gallery" do
        image_tag i.file.url, alt: "#{i.name}"
      end
    elsif i.audio?
      link_to i.file.url, class: "mfp-iframe", id: "gallery" do
        image_tag "audio.png", alt: "#{i.name}"
      end
    elsif i.video?
      link_to i.file.url, class: "mfp-iframe", id: "gallery" do
        image_tag "video.png", alt: "#{i.name}"
      end
    else
      link_to "", id: "gallery" do
        image_tag "doc.png", alt: "#{i.name}"
      end
    end
  end
end

app/views/folders/_small_modal.html.slim
#mySmallModal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      = form_tag nil, id: 'edit_folder_form', method: 'put' do
        .modal-body
          = text_field_tag :name
        .modal-footer
          = submit_tag "Змінити", class: "btn btn-primary"
          button.btn.btn-default data-dismiss="modal" type="button" Закрити

app/views/folders/destroy.js.erb
$('main').prepend("<%= j render partial: 'layouts/messages' %>")

app/views/folders/show.html.slim
= render 'small_modal'
section.Collage.effect-parent.gallery
  - @folder.children.each do |folder|
    .Image_Wrapper data-caption="<div class='text-center'>#{folder.name}<br>
      <a href='#' data-target='#mySmallModal' data-toggle='modal' class='edit-folder-name btn btn-default btn-xs'
      data-folder-name=#{folder.name} data-folder-id=#{folder.id}>
      <span class='glyphicon glyphicon-pencil'></span></a>
      <a href='#{folder_path(folder.id)}' data-method='delete' class='btn btn-default btn-xs'><span class='glyphicon glyphicon-trash'></span></a>
      </div>"
      = link_to folder_path(folder.id)
        = image_tag 'folder.png', alt: "#{folder.name}"
  - @folder.items.each do |i|
    .Image_Wrapper data-caption="<div class='text-center'>#{i.name}<br>
      <a href='javascript:' id='d_clip_#{i.id}' type='button' class='d_clip btn btn-default btn-xs' data-file-url='#{user_item_url(i.token, user_id: i.user_id)}'><span class='glyphicon glyphicon-share-alt'></span></a>
      <a href='#{item_download_my_path(i.id)}' class='btn btn-default btn-xs'><span class='glyphicon glyphicon-download-alt'></span></a>
      <a href='#{item_path(i.id)}' data-method='delete' class='btn btn-default btn-xs'><span class='glyphicon glyphicon-trash'></span></a>
      </div>"
      - if content_verification(i.file) == 1
        = link_to i.file.url, id: "gallery"
          = image_tag i.file.url, alt: "#{i.name}"
      - if content_verification(i.file) == 2
        = link_to i.file.url, class: "mfp-iframe", id: "gallery"
          = image_tag "audio.png", alt: "#{i.name}"
      - if content_verification(i.file) == 3
        = link_to i.file.url, class: "mfp-iframe", id: "gallery"
          = image_tag "video.png", alt: "#{i.name}"
      - if content_verification(i.file) == 0
        = link_to "", id: "gallery"
          = image_tag "docs.png", alt: "#{i.name}"

app/views/items/_items.html.slim
section.Collage.effect-parent.gallery
  - @folders.each do |folder|
    .Image_Wrapper id="folder_#{folder.id}" data-caption="<div class='editable text-center'>#{folder.name}<br>
      <a href='#' data-target='#mySmallModal' data-toggle='modal' class='edit-folder-name btn btn-default btn-xs'
      data-folder-name=#{folder.name} data-folder-id=#{folder.id}>
      <span class='glyphicon glyphicon-pencil'></span></a>
      <a href='#{folder_path(folder.id)}' data-folder-id='#{folder.id}' data-method='delete' class='btn btn-default btn-xs folder_destroy' data-remote='true'><span class='glyphicon glyphicon-trash'></span></a>
      </div>"
      = link_to folder_path(folder.id)
        = image_tag 'folder.png', alt: "#{folder.name}"
  - @items.each do |i|
    .Image_Wrapper id="item_#{i.id}" data-caption="<div class='editable text-center'>#{i.name}<br>
      <a href='javascript:' id='d_clip_#{i.id}' type='button' class='d_clip btn btn-default btn-xs' data-file-url='#{user_item_url(i.token, user_id: i.user_id)}'><span class='glyphicon glyphicon-share-alt'></span></a>
      <a href='#{item_download_my_path(i.id)}' class='btn btn-default btn-xs'><span class='glyphicon glyphicon-download-alt'></span></a>
      <a href='#{item_path(i.id)}' data-item-id='#{i.id}' data-method='delete' class='btn btn-default btn-xs item_destroy' data-remote='true'><span class='glyphicon glyphicon-trash'></span></a>
      </div>"
      = check_render_file(i)

app/views/items/_modal.html.slim
#myModal.modal.fade aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-label="Close" data-dismiss="modal" type="button"
          span aria-hidden="true"  &times;
        h4#myModalLabel.modal-title Щоб розпочати, натисніть, або перенесіть файли, в середину вікна.
      .modal-body
        = simple_form_for(@item, html: { class: 'dropzone text-center', id: 'drop-zone' }) do |f|
          - f.input :folder_id, as: :hidden, input_html: { value: params[:id] }
      .modal-footer
        button.btn.btn-default data-dismiss="modal" type="button" Закрити

app/views/items/destroy.js.erb
//new Item().destroy();
$('main').prepend("<%= j render partial: 'layouts/messages' %>")

app/views/items/edit.html.slim
.container
  .row
    .col-sm-6
      h2 = @item.name
      - if content_verification(@item.file) == 1
        = link_to i.file.url, title: "#{@item.name}", 'data-gallery' => ""
          = image_tag i.file.url, alt: "#{@item.name}"
      = audio_tag @item.file.url, controls: true if content_verification(@item.file) == 2
      - if content_verification(@item.file) == 3
        .embed-responsive.embed-responsive-16by9
          iframe.embed-responsive-item src="#{@item.file.url}"
      = image_tag "document-icon.png" if content_verification(@item.file) == 0
    .col-sm-6
      = simple_form_for(@item, html: { class: 'form-horizontal' }) do |f|
        = f.input :name, placeholder: "#{@item.name}", class: 'form-control'
        = f.button :submit, class: 'btn btn-primary'

app/views/items/index.html.slim
= render partial: "folders/small_modal"
#items-content data-no-turbolink=true
  = render 'items'

app/views/items/index.js.erb
$('#items-content').html("<%= j render partial: 'items/items' %>");
new Collage().init();

app/views/items/show.html.slim
section.Collage.effect-parent
  .Image_Wrapper data-caption="<div class='text-center'>#{@item.name}<br>
    <a href='#{download_items_path(id: @item.token, user_id: @item.user_id)}' id='download_link', class='btn btn-default btn-xs'>
      <span class='glyphicon glyphicon-download-alt'></span>
    </a>
    </div>"
    .gallery
      - if content_verification(@item.file) == 1
        = link_to @item.file.url, id: "gallery"
          = image_tag @item.file.url, alt: "#{@item.name}"
      - if content_verification(@item.file) == 2
        = link_to @item.file.url, class: "mfp-iframe", id: "gallery"
          = image_tag "audio.png", alt: "#{@item.name}"
      - if content_verification(@item.file) == 3
        = link_to @item.file.url, class: "mfp-iframe", id: "gallery"
          = image_tag "video.png", alt: "#{@item.name}"
      - if content_verification(@item.file) == 0
        = link_to "", id: "gallery"
          = image_tag "docs.png", alt: "#{@item.name}"

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-inverse
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: 'navbar-brand', style: 'padding: 0px;'
        = image_tag "logo.png"
    .collapse.navbar-collapse
      div style="font-size: 18px"
        ul.nav.navbar-nav.pull-right
          == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- if current_user
  li = link_to 'Створити теку...', folders_path(parent_id: params[:id]), method: 'post'
  li = link_to 'Завантажити файли...', '#', 'data-target' => "#myModal", 'data-toggle' => "modal"
  li = link_to 'Вихід', session_path(current_user), method: 'delete'
- else
  li = link_to 'Реєстрація', new_user_path
  li = link_to 'Увійти', new_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Collage'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Collage'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      = render partial: "items/modal"
      div data-pjax-container='data-pjax-container'
        == yield

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/profiles/_address_fields.html.slim
.nested-fields
  = f.input :country, as: :string
  = f.input :city
  = f.input :street
  = f.input :house_number
  = link_to_remove_association "remove address", f, class: "profile btn btn-danger"

app/views/profiles/_form.html.slim
= simple_form_for @profile do |f|
  section.Collage.effect-parent.gallery
    = link_to @profile.photo.url, id: "gallery"
      = image_tag(@profile.photo.url)
  = f.file_field :photo
  = f.input :name
  = f.input :birthday, as: :string, input_html: { class: 'datepicker', value: @profile.birthday.strftime("%d/%m/%Y"), 'data-provide' => 'datepicker' }
  h3 Адреси
  #addresses
    = f.simple_fields_for :addresses do |a|
      = render 'address_fields', f: a
    .links
      = link_to_add_association 'add address', f, :addresses, class: "profile btn btn-primary"
  = f.submit 'Оновити профіль', class: "btn btn-success"

app/views/profiles/edit.html.slim
h1.text-center Профіль
= render 'form'

app/views/users/_error_messages.html.slim
/- if @user.errors.any?
  - @user.errors.full_messages.each do |msg|
    .alert.alert-danger
      span.glyphicon.glyphicon-exclamation-sign
      span.sr-only
      = msg

app/views/users/new.html.slim
h1.text-center Реєстрація
.row
  .col-md-6.col-md-offset-3
    = render 'error_messages'
    = simple_form_for(@user, html: { class: 'form-horizontal' }) do |f|
      = f.input :email
      = f.input :password
      = f.input :password_confirmation
      = f.button :submit, 'Зареєструватися', class: 'btn btn-primary'

app/views/visitors/index.html.erb
<h3>Welcome</h3>